export const FETCH_API_REQUEST = "FETCH_API_REQUEST";
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
export const FETCH_API_FAILURE = "FETCH_API_FAILURE";
export const SET_START_END_DATES = "SET_START_END_DATES";
export const COMBINE_OBJECT_ARRAYS = "COMBINE_OBJECT_ARRAYS";
